### ISSUE TITLE
Cleaner spans

### ISSUE THREAD

**Issue by Yamakaky** [chrisguidry/pytest-opentelemetry#11]
This is a meta issue about a few things that could be improved about metadata of the spans. I'm doing some tests about what would be best, and should push a PR at some point.

- The root span is named "test run" with no meaningful attributes. It would be nice to be able to customize it. Not sure how though, maybe an env variable for start?
- The span name uses `node.nodeid`  for its name instead of `node.name` which doesn't include the filename. This info can be found in `code.filepath` anyway.
- `code.function` should use `item.name`.
- `code.lineno` can be 0 when running from a Tavern yaml file, maybe only include it when `> 0`. Otel supports ints so no need to `str(line_number)`.
- (wont do) `start_as_current_span` has optional attributes that can auto record exceptions https://opentelemetry-python.readthedocs.io/en/latest/api/trace.html#opentelemetry.trace.Tracer.start_as_current_span

**Comment by Yamakaky** [comment]
Oh, ok, i missed it, then i don't have to specify it everywhere! `trace` is stable in the python sdk so default changes shouldn't happen.

**Comment by chrisguidry** [comment]
> I'm doing some tests about what would be best, and should push a PR at some point.

Thanks for considering contributing, it's definitely welcome!  Feel free to send along PRs of any size.

I had some more detailed thoughts about your suggestions than I had time to share this morning:

> * The root span is named "test run" with no meaningful attributes. It would be nice to be able to customize it. Not sure how though, maybe an env variable for start?

Yes, please!  I don't have any compelling ideas about what to use here, but I look forward to your proposal.

> * The root span stays in status success even if a test fails.

Oof, you're right, that's definitely a bug.  I didn't notice it before because I usually look at the spans in Jaeger and it shows the nested errors (but the span itself is a success :facepalm:)

![image](https://user-images.githubusercontent.com/8194/189006551-402f2da9-5ba7-4d24-8136-d3313e5099dd.png)


> * The span name uses `node.nodeid`  for its name instead of `node.name` which doesn't include the filename. This info can be found in `code.filepath` anyway.

I'm not sure if this will match people's expectations.  The `dir/dir/file.py::test_name[param]` format to refer a single test is pretty deeply embedded in `pytest`.  It's how you refer to a specific test to run on the command-line as well.  Not sure if this would be the best change.  Send along some screenshots with the PR of how it looks?

> * `code.function` should use `item.name`.

Interesting, in my cursory testing, it looked like `item.name` was the same as the `item.location[2]`.  Do you know what the difference is?  I'd be on board with changing that if it helps to identify tests from alternative sources (like `tavern`, which you just taught me about)

> * `code.lineno` can be 0 when running from a Tavern yaml file, maybe only include it when `> 0`. Otel supports ints so no need to `str(line_number)`.

Good call!

**Comment by Yamakaky** [comment]
span name: I think I'll start with an env variable since it fits my usecase.

span status: I tried to fix this but I'm not familiar enough with pytest to do it. Help is welcome!

test name: my issue with that is that the span name gets very long especially in my case where where I have like `tests/functionsl/administration/funcx_test1.yaml::my_test[<three lines of params>]`, which is not very readable. Since the file name and params could be in the attributes, I'd rather have a span name `my_test[simplified_param_list]`, with configurable param that match summaries what the parameter contains. In my case, I have a device name, ip, description, url, credentials and other parameters, which in my case can be summaried by `[this_device]`.

code.function: I have to re test, it may be because of absolute vs relative path.

**Comment by chrisguidry** [comment]
> span status: I tried to fix this but I'm not familiar enough with pytest to do it. Help is welcome!

No worries, I can take a look into that, I split it out in #14 

> code.function: I have to re test, it may be because of absolute vs relative path.

Yes please let me know what you find, this might be a difference between tests in Python and Tavern tests in YAML.  I'd love to have good natural support for non-Python test suite plugins.
